[versions]
agp = "8.1.3"
appcompat = "1.7.0"
material = "1.11.0"
constraintlayout = "2.1.4"
activity = "1.8.2"
room = "2.6.1"

junit = "4.13.2"
espressoCore = "3.5.1"
extJunit = "1.1.5"
roomCommonJvm = "2.8.4"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# ‚≠ê Room Libraries
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
